var CITIES = [
  { t: "WildcardBurg", v: "*",           group: "Any" },
  { t: "Netherlands" },
	{ t: "Amsterdam",    v: "amsterdam",   group: "NL" },
	{ t: "Utrecht",      v: "utrecht",     group: "NL" },
	{ t: "Maastricht",   v: "maastricht",  group: "NL" },
  { t: "Belium" },
	{ t: "Bruxelles",    v: "bruxelles",   group: "BE" },
	{ t: "Bruges",       v: "bruges",      group: "BE" },
	{ t: "Antwerpen",    v: "antwerpen",   group: "BE" },
  { t: "France" },
	{ t: "Paris",        v: "paris",       group: "FR" },
  { t: "Lyon",         v: "lyon",        group: "FR" },
  { t: "Strasbourg",   v: "strasbourg",  group: "FR" },
  { t: "Nice",         v: "nice",        group: "FR" },
  { t: "Cannes",       v: "cannes",      group: "FR" },
  { t: "Marseilles",   v: "marseilles",  group: "FR" },
  { t: "Germany" },
  { t: "Aachen",       v: "aachen",      group: "DE" },
	{ t: "Frankfurt",    v: "frankfurt",   group: "DE" },
	{ t: "Berlin",       v: "berlin",      group: "DE" },
	{ t: "Munchen",      v: "munchen",     group: "DE" },
	{ t: "Mainz",        v: "mainz",       group: "DE" },
	{ t: "Köln",         v: "köln",        group: "DE" },
	{ t: "Düsseldorf",   v: "düsseldorf",  group: "DE" },
  { t: "United Kingdom" },
	{ t: "London",       v: "london",      group: "UK" },
  { t: "Manchester",   v: "manchester",  group: "UK" },
  { t: "Brighton",     v: "brighton",    group: "UK" },
  { t: "Birmingham",   v: "birmingham",  group: "UK" },
  { t: "Australia" },
  { t: "Pert",         v: "pert",        group: "AU" },
  { t: "Sydney",       v: "sydney",      group: "AU" },
  { t: "Canberra",     v: "canberra",    group: "AU" },
  { t: "Japan" },
	{ t: "Kyoto",        v: "kyoto",       group: "JP" },
	{ t: "Osaka",        v: "osaka",       group: "JP" },
	{ t: "Tokyo",        v: "tokyo",       group: "JP" },
	{ t: "Sapporo",      v: "sapporo",     group: "JP" },
	{ t: "Satsuma",      v: "satsuma",     group: "JP" },
  { t: "Russia" },
	{ t: "Москва",       v: "moscow",      group: "RU" },
	{ t: "Владивосток",  v: "vladivostok", group: "RU" },
  { t: "Одеса",        v: "odessa",      group: "RU" },
  { t: "Сочи",         v: "sochi",       group: "RU" },
  { t: "Волгоград",    v: "volgograd",   group: "RU" },
  { t: "Macedonia" },
  { t: "Скопје",       v: "skopje",      group: "MK" },
  { t: "Битола",       v: "bitola",      group: "MK" },
  { t: "Тетово",       v: "tetovo",      group: "MK" }
];